/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/blender_logo.glb -t -o src/components/sections/BlenderLogo.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve032: THREE.Mesh
    Curve033: THREE.Mesh
    Curve034: THREE.Mesh
  }
  materials: {
    ['SVGMat.026']: THREE.MeshStandardMaterial
    ['SVGMat.027']: THREE.MeshStandardMaterial
  }
}

export function BlenderLogo(props: any) {
  const { nodes } = useGLTF('/models/blender_logo.glb') as any

  return (
    <group {...props} dispose={null}>
      {/* Matte Glass Part (Curve032) */}
      <mesh geometry={nodes.Curve032.geometry} position={[0, 0.01, 0]}>
        <meshPhysicalMaterial
          transmission={1}
          thickness={1}
          roughness={0.2}
          transparent
          opacity={0.5}
          color="#ffffff"
        />
      </mesh>
      {/* Blue Part (Curve033) */}
      <mesh geometry={nodes.Curve033.geometry} position={[0, 0.03, 0]}>
        <meshStandardMaterial color="#265787" roughness={0.1} metalness={0.2} emissive="#265787" emissiveIntensity={1.0} />
      </mesh>
      {/* Orange Part (Curve034) */}
      <mesh geometry={nodes.Curve034.geometry} position={[0, 0.03, 0]}>
        <meshStandardMaterial color="#E87D0D" roughness={0.05} metalness={0.5} emissive="#E87D0D" emissiveIntensity={1.0} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/blender_logo.glb')
